// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEx4oai1vqgj3vJqTxy-ZChUWGA-6XduU',
    appId: '1:678652111557:web:9005f169a8173f1dac1eac',
    messagingSenderId: '678652111557',
    projectId: 'test-todos-app',
    authDomain: 'test-todos-app.firebaseapp.com',
    storageBucket: 'test-todos-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYYlI7gBerelcr6ByleO3SlqEVug58dkY',
    appId: '1:678652111557:android:6cebb869a9cbaf0eac1eac',
    messagingSenderId: '678652111557',
    projectId: 'test-todos-app',
    storageBucket: 'test-todos-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0fQ36ri-lD4elv7rNA7cAXAReMQeb4Xk',
    appId: '1:678652111557:ios:7d23046a33319324ac1eac',
    messagingSenderId: '678652111557',
    projectId: 'test-todos-app',
    storageBucket: 'test-todos-app.appspot.com',
    iosClientId: '678652111557-53tmcejvk8lcahd4evce8rhpsvem7rp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );
}
